#!/usr/bin/env python3
"""
Dispatch PRNG analysis to local models.
Goal: Find if k[1..70] could be generated by a PRNG.
"""
import sqlite3
import subprocess
import json

# Load k values
conn = sqlite3.connect('/home/solo/ladder/db/kh.db')
cur = conn.cursor()
k_values = {}
for n in range(1, 71):
    cur.execute('SELECT priv_hex FROM keys WHERE puzzle_id = ?', (n,))
    row = cur.fetchone()
    if row:
        k_values[n] = int(row[0], 16)
conn.close()

# Prepare data summary for the model
data_summary = """
k[1] = 1
k[2] = 3
k[3] = 7
k[4] = 8
k[5] = 21
k[6] = 49
k[7] = 76
k[8] = 224
k[9] = 467
k[10] = 514
k[11] = 1155
k[12] = 2683
k[13] = 5216
k[14] = 10544
k[15] = 26867
k[16] = 51510
k[17] = 95823
k[18] = 198669
k[19] = 357535
k[20] = 863317
"""

# Compute some patterns
patterns = []
for n in range(2, 21):
    ratio = k_values[n] / k_values[n-1]
    diff = k_values[n] - k_values[n-1]
    patterns.append(f"k[{n}]/k[{n-1}] = {ratio:.4f}, diff = {diff}")

prompt = f"""You are analyzing the Bitcoin puzzle k-sequence to find if it could be generated by a PRNG.

DATA:
{data_summary}

PATTERNS:
{chr(10).join(patterns[:15])}

KEY OBSERVATIONS:
- k[1,2,3] = 1, 3, 7 are Mersenne-like (2^n - 1)
- k[4] = 8 = 2^3 (exact power of 2)
- k[5] = 21 = 3 × 7 = k[2] × k[3]
- k[6] = 49 = 7² = k[3]²
- k[10] = 514 = 2^9 + 2 (only 2 bits set)

VERIFIED FORMULA:
k[n] = 2*k[n-1] + adj[n]
where adj[n] = k[n] - 2*k[n-1]

TASK:
1. Could this sequence be generated by a Linear Congruential Generator (LCG)?
2. Could it be from a Linear Feedback Shift Register (LFSR)?
3. What PRNG structure could produce these specific values?
4. Is there a seed that would generate k[1..20]?

Provide mathematical analysis, not guesses. Show your reasoning.
"""

print("=" * 70)
print("DISPATCHING PRNG ANALYSIS TO LOCAL MODEL")
print("=" * 70)
print()

# Run with deepseek
try:
    result = subprocess.run(
        ['ollama', 'run', 'deepseek-v3.1:671b-cloud', prompt],
        capture_output=True,
        text=True,
        timeout=300
    )
    print("### DeepSeek V3.1 Response ###")
    print(result.stdout[:3000] if result.stdout else "No output")
    if result.stderr:
        print("STDERR:", result.stderr[:500])
except subprocess.TimeoutExpired:
    print("Model timed out after 5 minutes")
except Exception as e:
    print(f"Error: {e}")

print()
print("=" * 70)
