#!/bin/bash
# Quick reference for binary pattern analysis findings

echo "================================================================================"
echo "BITCOIN PUZZLE BINARY PATTERN ANALYSIS - KEY FINDINGS"
echo "================================================================================"
echo ""
echo "Task: Binary Pattern Analysis (TASK 8)"
echo "Date: 2025-12-21"
echo "Data: k[1-70] from /home/rkh/ladder/db/kh.db"
echo ""
echo "================================================================================"
echo "CRITICAL DISCOVERY: BIT LENGTH CONSTRAINT"
echo "================================================================================"
echo ""
echo "★★★ ALL 70 KEYS have bit_length(k[n]) == n ★★★"
echo ""
echo "This means:"
echo "  - k[1] has exactly 1 bit  (range: [1, 1])"
echo "  - k[2] has exactly 2 bits (range: [2, 3])"
echo "  - k[3] has exactly 3 bits (range: [4, 7])"
echo "  - k[n] has exactly n bits (range: [2^(n-1), 2^n - 1])"
echo ""
echo "Implications for unsolved puzzles:"
echo "  - k[71] must be in range [2^70, 2^71 - 1]"
echo "  - k[71] ≈ [1.18 × 10^21, 2.36 × 10^21]"
echo "  - This HALVES the search space!"
echo ""
echo "================================================================================"
echo "PATTERN SUMMARY"
echo "================================================================================"
echo ""
echo "1. POPCOUNT (number of 1-bits):"
echo "   - Range: 1 to 38"
echo "   - Average: 18.04"
echo "   - Correlation with n: 0.9687 (STRONG positive correlation)"
echo ""
echo "2. RUN LENGTHS (consecutive 0s and 1s):"
echo "   - Max consecutive 1s: 10 (puzzle 56)"
echo "   - Max consecutive 0s: 9 (puzzle 51)"
echo "   - Average longest run of 1s: 3.89"
echo "   - Average longest run of 0s: 4.10"
echo ""
echo "3. HAMMING DISTANCE (between consecutive keys):"
echo "   - Range: 1 to 42"
echo "   - Average: 18.74"
echo "   - Median: 19"
echo "   - Small distances (≤5): 8/69 cases"
echo "   - Large distances (≥15): 40/69 cases"
echo ""
echo "4. XOR PATTERNS (k[n] XOR k[n-1]):"
echo "   - Range: varies widely"
echo "   - Powers of 2: 2/69 (2.9%)"
echo "     * k[2] XOR k[1] = 2 = 2^1"
echo "     * k[3] XOR k[2] = 4 = 2^2"
echo "   - Average XOR popcount: 18.74"
echo ""
echo "5. BIT COUNT vs PUZZLE NUMBER:"
echo "   - Average difference (popcount - n): -17.46"
echo "   - First 3 keys: perfect match (popcount == n)"
echo "   - After k[3]: generally popcount < n"
echo ""
echo "================================================================================"
echo "SPECIAL PATTERNS"
echo "================================================================================"
echo ""
echo "MERSENNE PATTERN (bootstrap):"
echo "  k[1] = 1   = 2^1 - 1 = binary: 1"
echo "  k[2] = 3   = 2^2 - 1 = binary: 11"
echo "  k[3] = 7   = 2^3 - 1 = binary: 111"
echo "  k[4] = 8   = 2^3     = binary: 1000 (transition!)"
echo ""
echo "LOW HAMMING WEIGHT (sparse keys):"
echo "  k[10] = 514 = binary: 1000000010 (only 2 ones, 20% density)"
echo "  k[8]  = 224 = binary: 11100000   (only 3 ones, 37.5% density)"
echo ""
echo "EXCEPTIONAL HAMMING DISTANCES:"
echo "  H(k[2], k[1]) = 1  (very small)"
echo "  H(k[3], k[2]) = 1  (very small)"
echo "  H(k[68], k[67]) = 42 (very large)"
echo ""
echo "================================================================================"
echo "FILES GENERATED"
echo "================================================================================"
echo ""
echo "1. binary_patterns.md - Full analysis report (464 lines)"
echo "   - Popcount table"
echo "   - Run length analysis"
echo "   - Hamming distance sequence"
echo "   - XOR pattern analysis"
echo "   - Complete binary table"
echo "   - Discovered regularities"
echo ""
echo "2. binary_pattern_analysis.py - Analysis script"
echo "   - Generates the markdown report"
echo "   - Can be re-run for verification"
echo ""
echo "3. binary_pattern_viz.py - Interactive visualization"
echo "   - Usage: python3 binary_pattern_viz.py <command>"
echo "   - Commands: progression, xor, bitdiff, interesting"
echo ""
echo "================================================================================"
echo "NEXT STEPS"
echo "================================================================================"
echo ""
echo "1. Review binary_patterns.md for detailed analysis"
echo "2. Use binary_pattern_viz.py to explore specific ranges"
echo "3. Consider how bit_length constraint affects k[71] search"
echo "4. Analyze correlation between popcount and puzzle number"
echo "5. Investigate why Hamming distances are generally large (avg 18.74)"
echo ""
echo "================================================================================"
